"""empty message

Revision ID: 1eed53175240
Revises: abfd9bdbd643
Create Date: 2022-07-29 00:38:34.218798

"""

# revision identifiers, used by Alembic.
revision = '1eed53175240'
down_revision = 'abfd9bdbd643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
