"""empty message

Revision ID: 9e679065d38e
Revises: 1eed53175240
Create Date: 2022-07-29 02:20:26.720963

"""

# revision identifiers, used by Alembic.
revision = '9e679065d38e'
down_revision = '1eed53175240'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
